"""
Cover-generator scaffolding template.

This module contains the constants and functions used by
`meta.bootstrap_domain._generate_cover_generator` to scaffold a
`domains/<name>/cover_generator.py` file from a profile.

Output structure (per generated file):
1. Module docstring (mentions domain + heuristic IDs)
2. Imports + small constants
3. Dataclasses: PoolState (or Session/Population for the domain), UserIntent, CoverParams
4. Per-heuristic cover strategy stub (one function per heuristic)
5. CoverGenerator class with .generate(intent) entry point that calls strategies
6. Example scenarios + main()

The generated file is guaranteed syntactically valid Python. Strategy bodies
are TODOs the user (or a follow-up LLM pass) must fill in with the actual
indistinguishability logic for each heuristic.
"""

from __future__ import annotations

from typing import Any


HEADER_TEMPLATE = '''"""
Cover generator for {domain_name}.

Auto-generated by meta/bootstrap_domain.py (cover_generator_template.py).

Goal: jointly optimize transaction parameters so the resulting tx is
maximally indistinguishable from the background population for this domain,
addressing each heuristic in profile.json:
{heuristic_summary}

This is a SKELETON. Each `_strategy_<HID>` function contains a TODO for the
domain-specific logic. The CoverGenerator.generate() entry point composes
all strategies.
"""

from __future__ import annotations

import json
import random
import statistics
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


PROFILE_PATH = Path(__file__).parent / "profile.json"


def _load_profile() -> dict:
    with open(PROFILE_PATH) as f:
        return json.load(f)


@dataclass
class PoolState:
    """Background population this user is trying to blend into.

    For privacy domains, this is the population of similar transactions /
    actions that already exist on-chain (or in the relevant context).
    Auto-generated structure; domain-specific fields can be added.
    """
    samples: list[dict] = field(default_factory=list)

    def size(self) -> int:
        return len(self.samples)


@dataclass
class UserIntent:
    """What the user wants to accomplish (raw, pre-cover)."""
    intent_type: str = ""
    target: str = ""
    amount: float = 0.0
    urgency: str = "normal"  # "immediate" | "normal" | "flexible"
    raw_params: dict = field(default_factory=dict)


@dataclass
class CoverParams:
    """Optimized parameters that maximize indistinguishability."""
    adjusted_params: dict = field(default_factory=dict)
    rationale: dict = field(default_factory=dict)  # {{heuristic_id: explanation}}
    expected_anonymity_set_size: int = 0


'''


STRATEGY_STUB_TEMPLATE = '''def _strategy_{hid_lower}(profile: dict, intent: UserIntent, pool: PoolState) -> dict:
    """Cover strategy for {hid}: {hname}

    Heuristic description (from profile):
    {hdescription}

    {strategy_hint}

    TODO: implement the actual indistinguishability logic. Return a dict of
    parameter adjustments + a "_reason" string explaining the cover choice.
    """
    h = profile["heuristics"]["{hkey}"]
    return {{
        # placeholder structure; fill in domain-specific adjustments
        "_heuristic_id": "{hid}",
        "_heuristic_name": h["name"],
        "_reason": "TODO: explain how this strategy obscures {hid}",
    }}


'''


COVER_GENERATOR_CLASS = '''@dataclass
class CoverGenerator:
    """Top-level cover generator. Composes all per-heuristic strategies."""
    profile: dict
    pool: PoolState

    @classmethod
    def from_profile(cls, pool: Optional[PoolState] = None) -> "CoverGenerator":
        return cls(profile=_load_profile(), pool=pool or PoolState())

    def generate(self, intent: UserIntent) -> CoverParams:
        adjusted = dict(intent.raw_params)
        rationale = {{}}

{strategy_calls}
        return CoverParams(
            adjusted_params=adjusted,
            rationale=rationale,
            expected_anonymity_set_size=self.pool.size(),
        )


'''


EXAMPLES_TEMPLATE = '''def run_examples():
    cg = CoverGenerator.from_profile()
    examples = [
        UserIntent(
            intent_type="example_action",
            target="0xexample",
            amount=1.0,
            urgency="normal",
            raw_params={"sample_param": 42},
        ),
    ]
    for i, intent in enumerate(examples, 1):
        print(f"\\n=== Example {i}: {intent.intent_type} ===")
        cover = cg.generate(intent)
        print(f"Adjusted params: {cover.adjusted_params}")
        print(f"Rationale: {cover.rationale}")
        print(f"Expected anonymity set: {cover.expected_anonymity_set_size}")


def main():
    print(f"Cover Generator: {_load_profile()['meta']['domain_name']}")
    run_examples()


if __name__ == "__main__":
    main()
'''


def heuristic_to_strategy_call(hid: str, hkey: str) -> str:
    return (
        f'        result_{hid.lower()} = _strategy_{hid.lower()}(self.profile, intent, self.pool)\n'
        f'        rationale["{hid}"] = result_{hid.lower()}.pop("_reason", "")\n'
        f'        adjusted.update({{k: v for k, v in result_{hid.lower()}.items() if not k.startswith("_")}})\n'
    )


def render(profile: dict, domain_name: str, strategy_hints: dict[str, str] | None = None) -> str:
    """Render a cover_generator.py for the given profile.

    strategy_hints: optional dict {hid: hint_paragraph} to fill in strategy docstrings.
    If None or missing for a heuristic, falls back to a generic TODO note.
    """
    strategy_hints = strategy_hints or {}
    heuristics = profile.get("heuristics", {})

    # Heuristic summary
    heuristic_summary_lines = []
    for hkey, h in heuristics.items():
        hid = h.get("id", hkey)
        hname = h.get("name", "")
        heuristic_summary_lines.append(f"  - {hid}: {hname}")
    heuristic_summary = "\n".join(heuristic_summary_lines) if heuristic_summary_lines else "  (no heuristics in profile)"

    parts: list[str] = [HEADER_TEMPLATE.format(
        domain_name=domain_name,
        heuristic_summary=heuristic_summary,
    )]

    # Strategy stubs
    for hkey, h in heuristics.items():
        hid = h.get("id", hkey)
        hname = h.get("name", "")
        hdescription = h.get("description", "(no description)")
        # Wrap long descriptions
        if len(hdescription) > 200:
            hdescription = hdescription[:200] + "..."
        hint = strategy_hints.get(hid, "Cover strategy is undefined; consult profile recommendations.")
        parts.append(STRATEGY_STUB_TEMPLATE.format(
            hid=hid,
            hid_lower=hid.lower(),
            hname=hname,
            hkey=hkey,
            hdescription=hdescription,
            strategy_hint=hint,
        ))

    # Cover generator class
    strategy_calls = ""
    for hkey, h in heuristics.items():
        hid = h.get("id", hkey)
        strategy_calls += heuristic_to_strategy_call(hid, hkey)
    parts.append(COVER_GENERATOR_CLASS.format(strategy_calls=strategy_calls))

    parts.append(EXAMPLES_TEMPLATE)

    return "".join(parts)


def strategy_hint_prompt(hid: str, hname: str, hdescription: str, recommendations: list[dict]) -> str:
    """Build a short LLM prompt to produce a strategy hint paragraph."""
    rec_text = "\n".join(
        f"- {r.get('action', '')}: {r.get('description', '')}"
        for r in recommendations[:3]
    )
    return f"""For heuristic {hid} ({hname}):

Description: {hdescription}

Existing recommendations:
{rec_text}

In one short paragraph (3-5 sentences), describe a "cover" strategy: how to ADJUST
transaction parameters so the heuristic's signal is OBSCURED in the resulting tx.
Focus on what to change (timing, amount, gas, source, format) rather than what to do
operationally. Be concrete. Do not write code; describe the strategy."""
