"""
Validation engine — automated property verification for generated domain profiles.

Checks:
  1. Sanitizer completeness: 0% FN on labeled sensitive spans
  2. False positive rate: <5% words removed from non-sensitive queries
  3. Profile completeness: >=95% of queries map to a subdomain
  4. Template coverage: >=60% of queries match a template
  5. Vocabulary depth: >=3 items per slot per subdomain
  6. Cover quality: adversary detection <= 40% (quick classifier)

Anti-malicious-LLM guardrails:
  7. Entity completeness: entities in dataset are covered by entity_names (anti-omission)
  8. Held-out sanitizer: test against independent data not generated by same LLM (anti-self-certification)
  9. Ontology balance: subdomain vocabularies are balanced in size (anti-fingerprinting)

Output: traffic-light report (PASS / MARGINAL / FAIL per property).
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

from core.profile_loader import load_profile


# ---------------------------------------------------------------------------
# Property 1: Sanitizer completeness
# ---------------------------------------------------------------------------

def check_sanitizer_completeness(
    profile: dict,
    span_results: list[dict],
) -> dict:
    """Test every labeled sensitive span against the sanitizer.

    Returns: {passed, total, false_negatives, fn_rate, verdict}
    """
    # Import cover_generator with this profile loaded
    import cover_generator as cg
    cg._init_from_profile(profile)

    total = 0
    false_negatives = []

    for entry in span_results:
        text = entry["text"]
        for span_info in entry.get("spans", []):
            span_text = span_info.get("span", "")
            if not span_text:
                continue
            total += 1
            sanitized = cg.sanitize_query(text)
            # Check if span survives sanitization
            if span_text.lower() in sanitized.lower():
                false_negatives.append({
                    "query": text,
                    "span": span_text,
                    "category": span_info.get("category", ""),
                    "sanitized_output": sanitized,
                })

    fn_rate = len(false_negatives) / max(total, 1)
    if fn_rate == 0:
        verdict = "PASS"
    elif fn_rate <= 0.05:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "passed": total - len(false_negatives),
        "total": total,
        "false_negatives": false_negatives,
        "fn_rate": round(fn_rate, 4),
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 2: False positive rate
# ---------------------------------------------------------------------------

def check_false_positive_rate(
    profile: dict,
    queries: list[dict],
) -> dict:
    """Check that non-sensitive queries are not over-stripped.

    Returns: {total_queries, avg_word_removal_rate, max_removal, verdict}
    """
    import cover_generator as cg
    cg._init_from_profile(profile)

    non_sensitive = [q for q in queries if q.get("label") != "sensitive"]
    if not non_sensitive:
        return {"total_queries": 0, "avg_word_removal_rate": 0, "verdict": "SKIP"}

    removal_rates = []
    worst = None
    for entry in non_sensitive:
        text = entry["text"]
        sanitized = cg.sanitize_query(text)
        original_words = len(text.split())
        remaining_words = len(sanitized.split())
        if original_words > 0:
            removed = 1 - (remaining_words / original_words)
            removal_rates.append(removed)
            if worst is None or removed > worst["rate"]:
                worst = {"query": text, "sanitized": sanitized, "rate": removed}

    avg_rate = sum(removal_rates) / max(len(removal_rates), 1)
    max_rate = max(removal_rates) if removal_rates else 0

    if avg_rate <= 0.05:
        verdict = "PASS"
    elif avg_rate <= 0.10:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "total_queries": len(non_sensitive),
        "avg_word_removal_rate": round(avg_rate, 4),
        "max_removal_rate": round(max_rate, 4),
        "worst_case": worst,
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 3: Profile completeness
# ---------------------------------------------------------------------------

def check_profile_completeness(
    profile: dict,
    queries: list[dict],
) -> dict:
    """Check that queries map to subdomains in the profile.

    Returns: {total, matched, coverage, unmatched_samples, verdict}
    """
    import cover_generator as cg
    cg._init_from_profile(profile)

    total = len(queries)
    matched = 0
    unmatched = []

    valid_domains = set(profile.get("subdomains", {}).keys())

    for entry in queries:
        domain = cg.classify_domain(entry["text"])
        if domain in valid_domains:
            matched += 1
        else:
            unmatched.append({"text": entry["text"], "classified_as": domain})

    coverage = matched / max(total, 1)
    if coverage >= 0.95:
        verdict = "PASS"
    elif coverage >= 0.80:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "total": total,
        "matched": matched,
        "coverage": round(coverage, 4),
        "unmatched_samples": unmatched[:10],
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 4: Template coverage
# ---------------------------------------------------------------------------

def check_template_coverage(
    profile: dict,
    queries: list[dict],
) -> dict:
    """Check that queries match templates with reasonable scores.

    Returns: {total, matched, coverage, avg_score, verdict}
    """
    import cover_generator as cg
    cg._init_from_profile(profile)

    total = len(queries)
    matched = 0
    scores = []

    for entry in queries:
        sanitized = cg.sanitize_query(entry["text"])
        template, score = cg._match_template(sanitized)
        scores.append(score)
        if score >= 2:
            matched += 1

    coverage = matched / max(total, 1)
    avg_score = sum(scores) / max(len(scores), 1)

    # Template matching is for cover generation, not query coverage.
    # Even the hand-crafted DeFi profile only matches ~55% of diverse queries.
    if coverage >= 0.60:
        verdict = "PASS"
    elif coverage >= 0.40:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "total": total,
        "matched": matched,
        "coverage": round(coverage, 4),
        "avg_score": round(avg_score, 2),
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 5: Vocabulary depth
# ---------------------------------------------------------------------------

def check_vocabulary_depth(profile: dict) -> dict:
    """Check that each subdomain has sufficient vocabulary.

    Returns: {subdomains_checked, deficient, details, verdict}
    """
    required_keys = [
        "protocols", "mechanisms", "operations", "triggers",
        "metrics", "actors", "risk_concepts", "generic_refs",
    ]
    # 3 is sufficient for cover generation; 5 is ideal for variety
    min_items = 3

    deficient = []
    checked = 0

    for sd_name, sd_data in profile.get("subdomains", {}).items():
        checked += 1
        for key in required_keys:
            items = sd_data.get(key, [])
            if len(items) < min_items:
                deficient.append({
                    "subdomain": sd_name,
                    "key": key,
                    "count": len(items),
                    "minimum": min_items,
                })

    if not deficient:
        verdict = "PASS"
    elif len(deficient) <= 3:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "subdomains_checked": checked,
        "deficient_slots": len(deficient),
        "details": deficient,
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 6: Cover quality (quick check)
# ---------------------------------------------------------------------------

def check_cover_quality(
    profile: dict,
    queries: list[dict],
    n_sets: int = 50,
) -> dict:
    """Quick cover quality check using string-similarity heuristic.

    A proper check would train a classifier; this is a fast approximation
    that checks if real queries are distinguishable by length/vocabulary overlap.

    Returns: {sets_tested, detection_rate, verdict}
    """
    import cover_generator as cg
    cg._init_from_profile(profile)

    sensitive = [q for q in queries if q.get("label") == "sensitive"]
    if not sensitive:
        sensitive = queries

    sample = sensitive[:n_sets]
    correct_guesses = 0
    total_tested = 0

    for entry in sample:
        try:
            shuffled, real_idx = cg.generate_cover_set(
                entry["text"], k=4,
                seed=int.from_bytes(entry["text"].encode()[:8], "big") & 0xFFFFFFFF,
            )
        except Exception:
            continue

        total_tested += 1

        # Heuristic detection: pick the query most different in length
        avg_len = sum(len(q) for q in shuffled) / len(shuffled)
        deviations = [abs(len(q) - avg_len) for q in shuffled]
        guess = deviations.index(max(deviations))

        if guess == real_idx:
            correct_guesses += 1

    detection_rate = correct_guesses / max(total_tested, 1)

    if detection_rate <= 0.30:
        verdict = "PASS"
    elif detection_rate <= 0.40:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "sets_tested": total_tested,
        "detection_rate": round(detection_rate, 4),
        "random_baseline": 0.25,
        "verdict": verdict,
        "note": "Heuristic check (length deviation). Full validation requires DistilBERT classifier.",
    }


# ---------------------------------------------------------------------------
# Property 7: Entity completeness (anti-omission guardrail)
# ---------------------------------------------------------------------------

def check_entity_completeness(
    profile: dict,
    queries: list[dict],
) -> dict:
    """Check that entity names in the dataset are covered by entity_names.

    Prevents the generating LLM from omitting key entities so the
    genericizer fails to strip them.

    Returns: {found_in_queries, covered, missed, coverage, verdict}
    """
    import re as _re

    entity_names = profile.get("sensitive_patterns", {}).get("entity_names", [])
    entity_set = set(e.lower() for e in entity_names)

    # Also collect all protocol names from subdomains
    for sd_data in profile.get("subdomains", {}).values():
        for proto in sd_data.get("protocols", []):
            entity_set.add(proto.lower())

    # Extract capitalized multi-word phrases from queries that look like entity names
    # (2+ chars, starts with uppercase, appears in multiple queries)
    candidate_counts: dict[str, int] = {}
    entity_pattern = _re.compile(r'\b[A-Z][a-zA-Z0-9]*(?:\s+(?:V\d+|[A-Z][a-zA-Z0-9]*))*\b')
    for entry in queries:
        found = set(entity_pattern.findall(entry["text"]))
        for ent in found:
            if len(ent) >= 2:
                candidate_counts[ent] = candidate_counts.get(ent, 0) + 1

    # Entities appearing 2+ times are likely real entity names
    found_in_queries = {ent for ent, count in candidate_counts.items() if count >= 2}

    covered = {ent for ent in found_in_queries if ent.lower() in entity_set}
    missed = found_in_queries - covered

    # Filter aggressively: entity completeness should only flag
    # protocol/product NAMES that the genericizer should strip, not
    # common English words, acronyms, or domain-general terms.
    skip_words = {
        "The", "This", "What", "How", "Why", "When", "Where", "Which",
        "Can", "Does", "Should", "Would", "Could", "Will", "My", "Is",
        "Are", "Do", "If", "For", "Not", "But", "Or", "And", "In", "On",
        "At", "To", "From", "By", "With", "About", "Into", "Through",
        "Best", "Most", "Some", "Any", "All", "Each", "Every", "Other",
        "Current", "Explain", "Compare", "Calculate", "Estimate",
        # Domain-general terms (not protocol names)
        "DeFi", "Ethereum", "Bitcoin", "Blockchain", "Web3", "Crypto",
    }
    missed = {
        e for e in missed
        if e not in skip_words
        and not e.isupper()           # all-caps = acronyms
        and not (e.endswith('s') and e[:-1].isupper())  # plural acronyms (AMMs, DEXes)
        and len(e) > 3                # skip short matches
        and not e.endswith('ing')     # skip gerunds
        and not e.endswith('ed')      # skip past tense
    }

    coverage = len(covered) / max(len(covered) + len(missed), 1)

    if coverage >= 0.70:
        verdict = "PASS"
    elif coverage >= 0.50:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "found_in_queries": len(covered) + len(missed),
        "covered": len(covered),
        "missed_entities": sorted(missed)[:20],
        "coverage": round(coverage, 4),
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 8: Held-out sanitizer test (anti-self-certification guardrail)
# ---------------------------------------------------------------------------

def check_held_out_sanitizer(
    profile: dict,
    held_out_queries: list[dict] | None = None,
) -> dict:
    """Test the sanitizer against a HELD-OUT test set not generated by the same LLM.

    This counters the self-certification attack: the generating LLM could
    coordinate patterns and test data to hide gaps. A held-out set provides
    independent validation.

    held_out_queries: list of {text, private_params: [str]} — params that MUST be stripped.
    If not provided, uses the hardcoded DeFi dataset's COMPLEX_QUERIES as default.

    Returns: {total_params, stripped, leaked, fn_rate, verdict}
    """
    import cover_generator as cg
    cg._init_from_profile(profile)

    if held_out_queries is None:
        # Use the hand-crafted dataset as held-out (independent of generation LLM)
        try:
            from dataset import COMPLEX_QUERIES
            held_out_queries = [
                {"text": q["query"], "private_params": q.get("private_params", [])}
                for q in COMPLEX_QUERIES
            ]
        except ImportError:
            return {"verdict": "SKIP", "reason": "No held-out data available"}

    # The sanitizer strips AMOUNTS/ADDRESSES/PERCENTAGES, not protocol names
    # or intent words (those are handled by the genericizer). Filter params
    # to only those the sanitizer is responsible for: numeric values, addresses,
    # percentages, health factors, leverage ratios.
    import re as _re
    _numeric_like = _re.compile(
        r'[\d$%.,]+|0x[a-fA-F0-9]+|health factor|leverage|\d+[xX]',
        _re.IGNORECASE,
    )

    if not held_out_queries:
        return {"verdict": "SKIP", "reason": "No held-out data provided"}

    total_params = 0
    leaked = []

    for entry in held_out_queries:
        text = entry.get("text", "")
        params = entry.get("private_params", [])
        sanitized = cg.sanitize_query(text)

        for param in params:
            # Only test params the sanitizer is responsible for (numeric/address/percentage)
            if not _numeric_like.search(param):
                continue
            total_params += 1
            param_clean = param.lower().replace(",", "")
            sanitized_clean = sanitized.lower().replace(",", "")
            if param_clean in sanitized_clean:
                leaked.append({"query": text, "param": param, "sanitized": sanitized})

    fn_rate = len(leaked) / max(total_params, 1)

    if fn_rate == 0:
        verdict = "PASS"
    elif fn_rate <= 0.05:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "total_params": total_params,
        "stripped": total_params - len(leaked),
        "leaked": leaked[:10],
        "fn_rate": round(fn_rate, 4),
        "verdict": verdict,
    }


# ---------------------------------------------------------------------------
# Property 9: Ontology balance (anti-fingerprinting guardrail)
# ---------------------------------------------------------------------------

def check_ontology_balance(profile: dict) -> dict:
    """Check that subdomain vocabularies are balanced in size.

    Imbalanced ontologies allow adversaries to fingerprint real queries by
    vocabulary richness — a subdomain with 50 terms vs one with 5 terms
    makes the 50-term subdomain's covers more varied and detectable.

    Returns: {subdomains, min_size, max_size, ratio, verdict}
    """
    vocab_sizes = {}
    for sd_name, sd_data in profile.get("subdomains", {}).items():
        if sd_name == "general":
            continue  # general is a catch-all, expect imbalance
        total = sum(
            len(sd_data.get(key, []))
            for key in ("mechanisms", "operations", "triggers", "metrics")
        )
        vocab_sizes[sd_name] = total

    if not vocab_sizes:
        return {"verdict": "SKIP", "reason": "No subdomains"}

    min_size = min(vocab_sizes.values())
    max_size = max(vocab_sizes.values())
    ratio = min_size / max(max_size, 1)

    if ratio >= 0.40:
        verdict = "PASS"
    elif ratio >= 0.20:
        verdict = "MARGINAL"
    else:
        verdict = "FAIL"

    return {
        "subdomains": vocab_sizes,
        "min_size": min_size,
        "max_size": max_size,
        "ratio": round(ratio, 4),
        "verdict": verdict,
        "note": "Ratio < 0.4 means one subdomain has 2.5x+ more vocabulary, aiding fingerprinting",
    }


# ---------------------------------------------------------------------------
# Full validation report
# ---------------------------------------------------------------------------

def validate_profile(
    profile_path: str | None = None,
    profile: dict | None = None,
    dataset_path: str | None = None,
    queries: list[dict] | None = None,
    span_results: list[dict] | None = None,
    progress: bool = True,
) -> dict:
    """Run all validation checks and produce a traffic-light report.

    Either provide profile_path (loads from disk) or profile (dict).
    Either provide dataset_path (loads JSONL) or queries (list of dicts).
    span_results is optional — needed for sanitizer completeness check.

    Returns: {properties: {name: result_dict}, summary: {pass, marginal, fail}}
    """
    if profile is None:
        if profile_path is None:
            raise ValueError("Must provide either profile or profile_path")
        profile = load_profile(profile_path)

    if queries is None:
        if dataset_path is None:
            raise ValueError("Must provide either queries or dataset_path")
        from meta.analyzer import load_dataset
        queries = load_dataset(dataset_path)

    results = {}

    # 1. Sanitizer completeness
    if span_results:
        if progress:
            print("Checking sanitizer completeness...")
        results["sanitizer_completeness"] = check_sanitizer_completeness(
            profile, span_results
        )
        if progress:
            r = results["sanitizer_completeness"]
            print(f"  {r['passed']}/{r['total']} spans stripped "
                  f"({r['verdict']})")
    else:
        results["sanitizer_completeness"] = {
            "verdict": "SKIP",
            "reason": "No span_results provided",
        }

    # 2. False positive rate
    if progress:
        print("Checking false positive rate...")
    results["false_positive_rate"] = check_false_positive_rate(profile, queries)
    if progress:
        r = results["false_positive_rate"]
        print(f"  Avg removal rate: {r.get('avg_word_removal_rate', 'N/A')} "
              f"({r['verdict']})")

    # 3. Profile completeness
    if progress:
        print("Checking profile completeness...")
    results["profile_completeness"] = check_profile_completeness(profile, queries)
    if progress:
        r = results["profile_completeness"]
        print(f"  {r['matched']}/{r['total']} queries matched "
              f"({r['verdict']})")

    # 4. Template coverage
    if progress:
        print("Checking template coverage...")
    results["template_coverage"] = check_template_coverage(profile, queries)
    if progress:
        r = results["template_coverage"]
        print(f"  {r['matched']}/{r['total']} queries matched "
              f"(avg score {r['avg_score']}) ({r['verdict']})")

    # 5. Vocabulary depth
    if progress:
        print("Checking vocabulary depth...")
    results["vocabulary_depth"] = check_vocabulary_depth(profile)
    if progress:
        r = results["vocabulary_depth"]
        print(f"  {r['deficient_slots']} deficient slots "
              f"({r['verdict']})")

    # 6. Cover quality
    if progress:
        print("Checking cover quality...")
    results["cover_quality"] = check_cover_quality(profile, queries)
    if progress:
        r = results["cover_quality"]
        print(f"  Detection rate: {r['detection_rate']} vs "
              f"{r['random_baseline']} random ({r['verdict']})")

    # 7. Entity completeness (anti-omission)
    if progress:
        print("Checking entity completeness...")
    results["entity_completeness"] = check_entity_completeness(profile, queries)
    if progress:
        r = results["entity_completeness"]
        print(f"  {r.get('covered', 0)}/{r.get('found_in_queries', 0)} entities covered "
              f"({r['verdict']})")

    # 8. Held-out sanitizer test (anti-self-certification)
    if progress:
        print("Checking held-out sanitizer...")
    results["held_out_sanitizer"] = check_held_out_sanitizer(profile)
    if progress:
        r = results["held_out_sanitizer"]
        if r["verdict"] != "SKIP":
            print(f"  {r.get('stripped', 0)}/{r.get('total_params', 0)} params stripped "
                  f"({r['verdict']})")
        else:
            print(f"  Skipped: {r.get('reason', '')}")

    # 9. Ontology balance (anti-fingerprinting)
    if progress:
        print("Checking ontology balance...")
    results["ontology_balance"] = check_ontology_balance(profile)
    if progress:
        r = results["ontology_balance"]
        if r["verdict"] != "SKIP":
            print(f"  Min/max ratio: {r.get('ratio', 'N/A')} ({r['verdict']})")
        else:
            print(f"  Skipped: {r.get('reason', '')}")

    # Summary
    verdicts = [r.get("verdict", "SKIP") for r in results.values()]
    summary = {
        "pass": sum(1 for v in verdicts if v == "PASS"),
        "marginal": sum(1 for v in verdicts if v == "MARGINAL"),
        "fail": sum(1 for v in verdicts if v == "FAIL"),
        "skip": sum(1 for v in verdicts if v == "SKIP"),
    }

    overall = "PASS"
    if summary["fail"] > 0:
        overall = "FAIL"
    elif summary["marginal"] > 0:
        overall = "MARGINAL"

    if progress:
        print(f"\n{'='*60}")
        print(f"VALIDATION SUMMARY: {overall}")
        print(f"  PASS: {summary['pass']}  MARGINAL: {summary['marginal']}  "
              f"FAIL: {summary['fail']}  SKIP: {summary['skip']}")
        print(f"{'='*60}")

    return {
        "properties": results,
        "summary": summary,
        "overall": overall,
    }
